name: base_flutter_bloc
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  # Main Dependencies
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # Network Dependencies
  dio: ^5.7.0
  retrofit: ^4.4.1

  # Local Storage Dependencies
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #  sqflite: ^2.3.3+1

  # Navigation Dependencies
  go_router: ^14.3.0

  # UI Dependencies
  google_fonts: ^6.2.1

  # Dependency Injection Dependencies
  get_it: ^8.0.1

  # Notifications Dependencies
  flutter_local_notifications: ^17.2.3

  # Permission Dependencies
  permission_handler: ^11.3.1

  # Annotation Dependencies
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Utils Dependencies
  collection: ^1.18.0
  cached_network_image: ^3.4.1
  synchronized: ^3.3.0
  chucker_flutter: ^1.8.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Main Dev Dependencies
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

  # Logger Dev Dependencies
  pretty_dio_logger: ^1.4.0

  # Dev Network Dependencies
  retrofit_generator: ^9.1.3
  json_serializable: ^6.8.0
  freezed: ^2.5.7

  flutter_lints: ^5.0.0

flutter:

  # The following line ensures that the Material Icons font is
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
